config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  resources :books#, only: [:new, :create, :index, :show, :edit, :destroy]
  resources :users, only: [:show, :edit, :index, :update]
  get 'home/about', to: 'homes#about', as: 'about'
  #get 'users', to: 'users#index', as: 'index_users'
  #get 'books', to: 'books#index', as: 'index_books'
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  resources :notifications, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
  
  has_many :notifications, as: :notifiable, dependent: :destroy
  
  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :notifications, dependent: :destroy
  
   has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  return profile_image.variant(resize_to_limit: [width, height]).processed
end

validates :name, presence: true
validates :name,  length: { minimum: 2 }
validates :name, length: { maximum: 20 }
validates :name, uniqueness: true
validates :introduction, length: { maximum: 50 }

GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)  
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path  # 投稿一覧画面へリダイレクト  
  end
  
  def get_profile_image(width, height)
    # プロフィール画像のパスを組み立てる
    profile_image_path = "/path/to/profile_images/#{self.profile_image_filename}"
    # プロフィール画像のURLを組み立てる
    profile_image_url = "http://example.com#{profile_image_path}"
    return profile_image_url
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def update
    notification = current_user.notifications.find(params[:id])
    notification.update(read: true)
    # 通知の種類によるリダイレクトパスの生成
    case notification.notifiable_type
    when "Book"
      redirect_to book_path(notification.notifiable)
    else
      redirect_to user_path(notification.notifiable.user)
    end
  end
end

app/controllers/users/sessions_controllers.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]
  def new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])  
    @books = @user.books   
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(current_user)  
    else
      render :edit
    end
  end
  
  def get_profile_image(width, height)
    # プロフィール画像のパスを組み立てる
    profile_image_path = "/path/to/profile_images/#{self.profile_image_filename}"
    # プロフィール画像のURLを組み立てる
    profile_image_url = "http://example.com#{profile_image_path}"
    return profile_image_url
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_message(notification)
    case notification.notifiable_type
    when "Book"
      "フォローしている#{notification.notifiable.user.name}さんが#{notification.notifiable.title}を投稿しました"
    else
      "投稿した#{notification.notifiable.book.title}が#{notification.notifiable.user.name}さんにいいねされました"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>

<%= form_with model: @book do |f| %>

<div class="form-group">
  <h4>Title</h4>
  <%= f.text_field :title %>
  </div>
  
  <div class="form-group">
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  </div>
  
  <div class="form-group">
  <%= f.submit 'Update Book', class:"btn btn-success" %>
  </div>
<% end %>

<li>
<%= link_to "Show", book_path(@book) %>
</li>

<li>
  <%= link_to "Back", books_path %>
</li>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
<%= render 'layouts/left', user: @user, book: @book %>

<div class='col-md-8 offset-md-1'>
<h1>Books<h1>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>
        Title
      </th>
      <th>
        Opinion
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <div>
        <%= link_to book_path(book.id) do %>
        <% end %>
        <tr>
          <td>
            <%= link_to(user_path(book.user)) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
          </td>
        <td>
    <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
          </td>
      </tr>
      </div>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book do |f| %>
<h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
<%= render 'layouts/left', user: @user, book: @new_book %>

<div class='col-md-8 offset-md-1'>
<h1>Book detail</h1>
<table class="table">
<div>
  <%= link_to(user_path(@book.user)) do %>
    <%= image_tag @book.user.get_profile_image(100,100) %>
  <% end %>
  <%= link_to(user_path(@book.user)) do %>
    <%= @book.user.name %>
  <% end %>
  <%= link_to @book.title, book_path(@book) %>
  <%= @book.body %>
  
  <% if @book.user == current_user %>
 <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>
<%= link_to "Destroy", book_path(@book), class:"btn btn-sm btn-danger",method: :delete, "data-confirm" => "本当に削除しますか？" %>
<% end %>
</div>
</div>
</table>
</div>
</div>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

app/views/homes/top.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <div class="row">
          <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 ' %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block' %>
            </div>
      </div>
  </div>
</div>

      </main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_left.html.erb
    <div class='col-md-3'>
<h1>User info</h1>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
</table>
<% if user.email != "guest@example.com" %>
<div class="row">
  <%= link_to "",edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

  <%= link_to  edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
<% end %>

<div class="mt-3">
  <h1>New book</h1>
  <% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <h4>Title</h4>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <h4>Opinion</h4>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/4e79a6d12f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path,  class: 'navbar-brand' do %>
            Bookers
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
      
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-home"></i>Home
                  <% end %>
                <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-users"></i>Users
                <% end %>
                <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-book-open"></i>Books
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-sign-out-alt"></i>Log out
                <% end %>
              <% else %>
                <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-home"></i>Home
                <% end %>
                <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-link"></i>About
                <% end %>
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-user-plus"></i>Sign up
                <% end %>
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class= "fa-solid fa-sign-in-alt"></i>Log in
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= flash[:notice] %>
    <%= yield %>
  
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_info.html.erb
<table class="table">
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>
<% if user.email != "guest@example.com" %>
  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
  <% unless user.guest_user? %>
<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model: @user do |f| %>
<div class="form-group">
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
  </div>
  <div class="form-group">
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %> 
  </div>
  <div class="form-group">
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction"%>
  </div>
  <%= f.submit "Update User", class:"btn btn-secondary" %>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
<%= render 'layouts/left', user: @user, book: @book %>

<div class='col-md-8 offset-md-1'>
<h1>Users</h1>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= image_tag user.get_profile_image(100,100) %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
          <li>
        <%= link_to "Show", user_path(user) %>
      </li>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>
  </div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render 'layouts/left', user: @user, book: @book %>

<div class='col-md-8 offset-md-1'>
<h1>Books</h1>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.user) do %>
            <%= image_tag book.user.get_profile_image(100, 100) %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>